In [1]:
import numpy as np

In [ ]:
a1 = np.array(['Spark', 'Hadoop', 'Python', 'R'])

# Método array

In [3]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

In [4]:
a2 = np.array([['altura', 'Largura', 'profundidade'], [42, 78, 10]])

In [5]:
a2

array([['altura', 'Largura', 'profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [6]:
print(a1.shape)

(4,)


In [7]:
print(a2.shape)

(2, 3)


In [8]:
a1.ndim

1

In [10]:
a2.ndim

2

In [11]:
a2.max()

TypeError: cannot perform reduce with flexible type

In [12]:
a3 = np.array([[10,20,30],[40,50,60]])

In [13]:
a3

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
a3.max()

60

# Método Arrange

In [17]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
array = np.arange(0, 100, 10)
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# criando estruturas de dados com linspace

In [21]:
matriz = np.linspace(0,10,20)
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
matriz = np.linspace(0,10,5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
matriz = np.linspace(0,5,5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

# Estruturas de Matrizes

In [24]:
matriz = np.zeros((10, 10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
matriz = np.ones((2,3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.tile(np.array([[1,2], [3,4], [5,6]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])