In [1]:
import numpy as np

In [2]:
a = [1,2,11,6,8,18,2]

array = np.array(a)

print(type(array))

<class 'numpy.ndarray'>


In [3]:
print(array.shape)

(7,)


In [4]:
array[0]

1

In [5]:
array[-1]

2

In [6]:
array[-2]

18

In [7]:
print(array[1:5])

[ 2 11  6  8]


In [8]:
print(array[1:5:2])

[2 6]


In [9]:
print(array[0:6:2])

[ 1 11  8]


In [19]:
print(array[-6:-3])

[ 2 11  6]


In [20]:
print(array[3:])

[ 6  8 18  2]


In [21]:
print(array[::-1])

[ 2 18  8  6 11  2  1]


In [ ]:
x = np.array([2,6,8,4])
y = np.array([11,8,2])
z = np.concatenate