In [3]:
import numpy as np

# Operações com Arrays Multidimensionais

In [6]:
A = [[1,2,3,4],[5,6,7,8],[10,20,30,40],[50,60,70,80]]

array = np.array(A)

print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [7]:
array[0]

array([1, 2, 3, 4])

In [8]:
print(array[2])

[10 20 30 40]


In [9]:
print(array[0,3])

4


In [10]:
array[0,0] = 0
print(array)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


# Trabalhando com intervalos

In [11]:
print(array[1:3,1:3])

[[ 6  7]
 [20 30]]


In [14]:
print(array[:,3])

[ 4  8 40 80]


In [16]:
print(array[3,:])

[50 60 70 80]


In [18]:
# Concatenando arrays multidimensionais
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]]


In [20]:
c = np.concatenate((A,B))
print(c)

[[1 2]
 [3 4]
 [5 6]]
