# operações aritméticas com arrays

In [3]:
import numpy as np

In [4]:
arrayA = np.arange(0,10)
arrayB = np.arange(0,10)+1

In [6]:
arrayA


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

# Dot Product

In [10]:
A = np.array([2,4,6])
B = np.array([2,2,2])

In [11]:
A * B

array([ 4,  8, 12])

In [12]:
print(np.dot(A,B))

24


# Cópias de Arrays

In [13]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
B = A[2:]
B

array([2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
A[:] = 0
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
B

array([0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
B = A[5:].copy()
B

array([5, 6, 7, 8, 9])

In [25]:
A[0:4] = 2
A

array([2, 2, 2, 2, 4, 5, 6, 7, 8, 9])

In [26]:
B

array([5, 6, 7, 8, 9])